export const DISABLED_COMMANDS = [
    "ASSOC",
    "ATTRIB",
    "BREAK",
    "BCDEDIT",
    "CACLS",
    "CALL",
    "CD",
    "CHCP",
    "CHDIR",
    "CHKDSK",
    "CHKNTFS",
    // "CLS",
    "CMD",
    // "COLOR",
    "COMP",
    "COMPACT",
    "CONVERT",
    "COPY",
    "DATE",
    "DEL",
    "DIR",
    "DISKPART",
    "DOSKEY",
    "DRIVERQUERY",
    "ECHO",
    "ENDLOCAL",
    "ERASE",
    "EXIT",
    "FC",
    "FIND",
    "FINDSTR",
    "FOR",
    "FORMAT",
    "FSUTIL",
    "FTYPE",
    "GOTO",
    "GPRESULT",
    "GRAFTABL",
    // "HELP",
    "ICACLS",
    "IF",
    "LABEL",
    "MD",
    "MKDIR",
    "MKLINK",
    "MODE",
    "MORE",
    "MOVE",
    "OPENFILES",
    "PATH",
    "PAUSE",
    "POPD",
    "PRINT",
    "PROMPT",
    "PUSHD",
    "RD",
    "RECOVER",
    "REM",
    "REN",
    "RENAME",
    "REPLACE",
    "RMDIR",
    "ROBOCOPY",
    "SET",
    "SETLOCAL",
    "SC",
    "SCHTASKS",
    "SHIFT",
    "SHUTDOWN",
    "SORT",
    "START",
    "SUBST",
    "SYSTEMINFO",
    "TASKLIST",
    "TASKKILL",
    "TIME",
    "TITLE",
    "TREE",
    "TYPE",
    "VER",
    "VERIFY",
    "VOL",
    "XCOPY",
    "WMIC"
]

export const COMMANDS = [
    {name: "CLS", desc: "Очистка экрана."},
    {name: "COLOR", desc: "Установка цвета текста в консоли."},
    {name: "HELP", desc: "Выводит справочную информацию о доступных командах."},
]

export const COLORS = [
    {name: "Белый", color: "#FFFFFF"},
    {name: "Зеленый", color: "#00FF00"},
    {name: "Желтый", color: "#FFFF00"},
    {name: "Красный", color: "#FF0000"},
    {name: "Розовый", color: "#FF00FF"},
    {name: "Синий", color: "#0000FF"},
    {name: "Голубой", color: "#00FFFF"},
]